MVCModelBindingHomework/Models/ErrorViewModel.cs
namespace MVCModelBindingHomework.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCModelBindingHomework/Models/Primarch.cs
using System.ComponentModel.DataAnnotations;

namespace MVCModelBindingHomework.Models
{
    public class Primarch
    {
        /// <summary>
        /// Full Name of the Primarch
        /// </summary>
        [Required(ErrorMessage = "Please provide the Primarch's name")]
        [Display(Name = "Primarch's Full Name")]
        public string Name { get; set; }

        /// <summary>
        /// Order in which the Primarch was created
        /// </summary>
        [Range(1, 20, ErrorMessage = "Must be a number between 1 and 20")]
        [Display(Name = "Legion Number")]
        public int LegionNumber { get; set; }

        /// <summary>
        /// The legion that belongs to the Primarch
        /// </summary>
        [Required(ErrorMessage = "Provide the Legion under this Primarch's command")]
        [Display(Name = "Legion of Command")]
        public string Legion { get; set; }

        /// <summary>
        /// The planer where each Primarch was found
        /// and which he considers home
        /// </summary>
        [Required(ErrorMessage = "Enter the world Claimed by the Primarch and his legion")]
        [Display(Name = "Primarch's Home World")]
        public string HomeWorld { get; set; }
    }
}

MVCModelBindingHomework/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCModelBindingHomework.Models;
using System.Diagnostics;

namespace MVCModelBindingHomework.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCModelBindingHomework/Controllers/PrimarchController.cs
using Microsoft.AspNetCore.Mvc;
using MVCModelBindingHomework.Models;

namespace MVCModelBindingHomework.Controllers
{
    public class PrimarchController : Controller
    {
        
        [HttpGet]
        public IActionResult CreateWithModelBinding()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateWithModelBinding(Primarch p)
        {
            if (ModelState.IsValid)
            {
                // PrimarchDb.Add(p);  Primarch data would be added to database here

                return RedirectToAction("Index", "Home");
            }
            // If model state isn't valid
            // show the page, but with validation errors
            return View(p);
        }
    }
}

MVCModelBindingHomework/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCModelBindingHomework/Views/Primarch/CreateWithModelBinding.cshtml
@model Primarch 
@{
	ViewData["Title"] = "Add a Primarch";
}

<h2>Add a Primarch</h2>

<form method="post">
	<div class="col-md-6">
		<div class="form-group">
			<label class="control-label" asp-for="Name"></label>
			<input class="form-control" asp-for="Name" />
			<span class="text-danger" asp-validation-for="Name"></span>
		</div>

		<div class="form-group">
			<label class="control-label" asp-for="LegionNumber"></label>
			<input class="form-control" asp-for="LegionNumber" />
			<span class="text-danger" asp-validation-for="LegionNumber"></span>
		</div>

		<div class="form-group">
			<label class="control-label" asp-for="Legion"></label>
			<input class="form-control" asp-for="Legion" />
			<span class="text-danger" asp-validation-for="Legion"></span>
		</div>

		<div class="form-group">
			<label class="control-label" asp-for="HomeWorld"></label>
			<div class="input-group mb-3">
				<input class="form-control" asp-for="HomeWorld" />
				<button class="btn btn-dark" type="submit" id="button-addon2">Add Primarch</button>
			</div>
			<span class="text-danger" asp-validation-for="HomeWorld"></span>
		</div>
	</div>
</form>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

MVCModelBindingHomework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCModelBindingHomework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCModelBindingHomework.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCModelBindingHomework</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Primarch" asp-action="CreateWithModelBinding">Add Primarch</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCModelBindingHomework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>